import "./build-icons.mjs";
import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname, relative } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const seen = new Set();
const chunks = [];
async function visit(path) {
  path = resolve(path);
  if (seen.has(path)) return;
  seen.add(path);
  let source = await readFile(path, 'utf8');
  const imports = [...source.matchAll(/^import\s+[\s\S]*?from\s+["']([^"']+)["'];?\s*$/gm)];
  const sideEffects = [...source.matchAll(/^import\s+["']([^"']+)["'];?\s*$/gm)];
  for (const match of [...imports, ...sideEffects]) {
    await visit(resolve(dirname(path), match[1]));
    source = source.replace(match[0], '');
  }
  source = source.replace(/^export\s*\{[\s\S]*?\};?\s*$/gm, '')
    .replace(/^export\s+(?=(?:const|let|function|async function|class)\b)/gm, '');
  chunks.push(`// ${relative(root, path)}\n${source.trim()}`);
}
await visit(resolve(root, 'src/app.js'));
await writeFile(resolve(root, 'dist/app.bundle.js'), `// Generated by npm run build. Edit src/, not this file.\n(() => {\n"use strict";\n${chunks.join('\n\n')}\n})();\n`);

// Keep local-file-compatible inline design tokens synchronized on every build.
const cssPath = resolve(root, 'styles/main.css');
const css = await readFile(cssPath, 'utf8');
const variables = await readFile(resolve(root, 'styles/variables.css'), 'utf8');
const variableRegion = /\/\* BEGIN GENERATED VARIABLES \*\/[\s\S]*?\/\* END GENERATED VARIABLES \*\//;
if (!variableRegion.test(css)) throw new Error('Main stylesheet is missing its generated variables region');
await writeFile(cssPath, css.replace(variableRegion, `/* BEGIN GENERATED VARIABLES */\n${variables}\n/* END GENERATED VARIABLES */`));
